### ISSUE TITLE
Google Folder ID

### ISSUE THREAD

**Issue by bryancross** [bryancross/key2pdf#19]
:wave: @tcbyrd ...  Can you provide an example folder ID?  Is this a secure item like an API key or PAT?  I think not having a folder ID is what's causing this error for me:

```
2017-02-01T09:53:15.190-02:00:    PATH: ./job/41a0957c746c6c68708479152ecac18bdfc3b43e/deck10.key.pdf
Error from API: 
 { Error: File not found: .
    at Request._callback (/Users/bryancross/dev/key2pdf/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/Users/bryancross/dev/key2pdf/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/bryancross/dev/key2pdf/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/bryancross/dev/key2pdf/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'File not found: .',
       locationType: 'parameter',
       location: 'fileId' } ] }

**Comment by tcbyrd** [comment]
@bryancross the folder I've been using for testing is `0Bx7UhUK81Pz1X0k4Um9xT2tveFE`

This is read from `/gdrive/config/google-config.json`:
```javascript
{
  "UrlApiKey": "<ApiKey for Google URL Shortener>",
  "UploadFolder": "<FolderId of a shared Google Drive Folder>"
}
```

It's not an API key. It's the *folderId* that google assigns to a folder when you create it. I did it this way because the thinking is that you use the Google Drive UI to create a folder and share it with the appropriate people first.

Does that work?

**Comment by bryancross** [comment]
Hi @tcbyrd 

I realize it's not an API key, my question was around whether it was sensitive info _like_ an API key.  I.e., whether it would be a bad idea to check it in :) 

I solved my problem.  I had two `google-config.json` files.  I guess at some point I started the process of consolidation...lolz.  

So we're all good.  Thanks again!!

**Comment by tcbyrd** [comment]
👍 

It **can** be safely shared, although you probably shouldn't to prevent it from becoming an attack vector. Permissions are tied to the Google account you authenticate to using the [OAuth Token](https://github.com/bryancross/key2pdf/blob/refactoring-to-modules/config/client_secret-example.json) acquired earlier in the program. If that account has write access to the folder ID, it will work. Otherwise it should fail with *I think* a `403 Forbidden`.
